import * as React from "react"

const MOBILE_BREAKPOINT = 768

// NOTE: generated by `shadcn add sidebar`, then rewritten to use
// useSyncExternalStore. The original set state inside an effect, which trips
// react-hooks/set-state-in-effect and fails `npm run lint`. Re-running the
// shadcn CLI will overwrite this file — reapply the change if it does.

const QUERY = `(max-width: ${MOBILE_BREAKPOINT - 1}px)`

function subscribe(onChange: () => void) {
  const mql = window.matchMedia(QUERY)
  mql.addEventListener("change", onChange)
  return () => mql.removeEventListener("change", onChange)
}

export function useIsMobile() {
  return React.useSyncExternalStore(
    subscribe,
    () => window.matchMedia(QUERY).matches,
    // Server render: assume desktop, matching the original's `!!undefined`.
    () => false
  )
}
